package bits;

import java.util.Arrays;
import java.util.List;

public class MaxAndValue {
//    Maximum AND value of a pair in an array
//Difficulty Level : Hard
//Last Updated : 26 May, 2021
//We are given an array of n positive elements. we need to find the maximum AND value generated by any pair of element from the array. AND is bitwise & operator.
//Examples:
//
//
//Input : arr[] = {4, 8, 12, 16}
//Output : Maximum AND value = 8
//
//Input : arr[] = {4, 8, 16, 2}
//Output : Maximum AND value = 0
    static int countSetBits(int pattern, List<Integer> numbers){
        int cnt=0;
        for(int num:numbers){
            if(pattern==(pattern&num)){
                cnt++;
            }
        }
        return cnt;
    }

    static int maxAndVal(List<Integer> numbers){
        int res=0;
        for(int i=31;i>=0;i--){
            int cnt=countSetBits(res|1<<i, numbers);
            if(cnt>=2){
                res|=(1<<i);
            }
        }
        return res;
    }

    public static void main(String[] args) {
        System.out.println(maxAndVal(Arrays.asList(4,8,2,16)));
    }
}
